/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/glb/fleet/FleetCard6.gltf 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useThree } from '@react-three/fiber'
import { motion } from "framer-motion-3d";

export default function FS6(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/src/glb/fleet/FleetCard6.gltf')
  const { actions } = useAnimations(animations, group)
  const { viewport } = useThree();

  const variant = {
    animate: {
      rotateY: [0, Math.PI * 2], // Rotate on the Y-axis
    },
    transition: {
      duration: 3, // Duration of one full rotation
      repeat: Infinity, // Infinite looping
      ease: "linear", // Smooth linear rotation
    }
  }
  return (
    <group ref={group} {...props} dispose={null} scale={viewport.width / 9}>
      <group name="Scene">
        <mesh name="Text" geometry={nodes.Text.geometry} material={nodes.Text.material} position={[2.536, 1.763, -0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.555}>
          <mesh name="GN_Instance" geometry={nodes.GN_Instance.geometry} material={nodes.GN_Instance.material} />
        </mesh>
        <motion.mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[3.521, 1.82, -0.001]} rotation={[0.896, -0.809, 0]} scale={0.047} />
        <motion.mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[3.404, 1.89, 0.007]} rotation={[0.896, -0.809, 0]} scale={0.029} />
        <motion.mesh animate={{
          rotateY: [0, -1 * Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle" geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[-3.191, 1.485, 0]} rotation={[1.569, 0.182, 0.004]} scale={0.489} />
        <motion.mesh animate={{
          rotateY: [0, - 1 * Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle001" geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[-3.333, 1.057, -0.011]} rotation={[1.569, 0.331, -0.008]} scale={0.26} />
        <motion.mesh animate={{
          rotateY: [0, -1 * Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle002" geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[-3.174, 1.878, -0.019]} rotation={[1.569, 0.242, -0.008]} scale={0.26} />
        <motion.mesh animate={{
          rotateY: [0, Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle003" geometry={nodes.Circle003.geometry} material={nodes.Circle003.material} position={[-2.492, 1.159, 0.003]} rotation={[1.569, 0.095, 0.005]} scale={0.363} />
        <motion.mesh animate={{
          rotateY: [0, Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle004" geometry={nodes.Circle004.geometry} material={nodes.Circle004.material} position={[-3.014, 1.177, 0.003]} rotation={[1.569, 0.182, 0.004]} scale={0.24} />
        <motion.mesh animate={{
          rotateY: [0, Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle005" geometry={nodes.Circle005.geometry} material={nodes.Circle005.material} position={[-2.689, 1.468, -0.015]} rotation={[1.569, 0.123, -0.007]} scale={0.26} />
        <motion.mesh animate={{
          rotateY: [0, Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle006" geometry={nodes.Circle006.geometry} material={nodes.Circle006.material} position={[2.551, -1.112, 0.025]} rotation={[1.577, 1.055, -0.009]} scale={0.491} />
        <motion.mesh animate={{
          rotateY: [0, -1 * Math.PI * 2]
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle007" geometry={nodes.Circle007.geometry} material={nodes.Circle007.material} position={[2.748, -1.448, 0.013]} rotation={[1.589, 1.287, -0.032]} scale={0.261} />
        <motion.mesh animate={{
          rotateY: [0, -1 * Math.PI * 2]
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle008" geometry={nodes.Circle008.geometry} material={nodes.Circle008.material} position={[3.189, -1.833, 0.016]} rotation={[1.57, -0.429, -0.002]} scale={0.261} />
        <motion.mesh animate={{
          rotateY: [0, Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle009" geometry={nodes.Circle009.geometry} material={nodes.Circle009.material} position={[3.281, -1.477, 0.029]} rotation={[1.569, 0.095, 0.005]} scale={0.474} />
        <motion.mesh animate={{
          rotateY: [0, -1 * Math.PI * 2]
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle010" geometry={nodes.Circle010.geometry} material={nodes.Circle010.material} position={[3.337, -1.028, 0.024]} rotation={[1.569, 0.182, 0.004]} scale={0.256} />
        <motion.mesh animate={{
          rotateY: [0, Math.PI * 2],
        }}
          transition={{
            duration: 5,
            repeat: Infinity,
            ease: "linear",
          }} name="Circle011" geometry={nodes.Circle011.geometry} material={nodes.Circle011.material} position={[3.038, -1.139, 0.01]} rotation={[1.569, -0.382, -0.003]} scale={0.261} />
      </group>
    </group>
  )
}

useGLTF.preload('/src/glb/fleet/FleetCard6.gltf')
