/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/glb/fleet/FleetCard5.gltf 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function FS5(props) {
  const group = React.useRef()
  const { nodes, materials, animations  } = useGLTF('/src/glb/fleet/FleetCard5.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Text" geometry={nodes.Text.geometry} material={nodes.Text.material} position={[2.536, 1.763, -0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.555}>
          <mesh name="GN_Instance" geometry={nodes.GN_Instance.geometry} material={nodes.GN_Instance.material} />
        </mesh>
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[3.521, 1.82, -0.001]} rotation={[0.896, -0.809, 0]} scale={0.047} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[3.404, 1.89, 0.007]} rotation={[0.896, -0.809, 0]} scale={0.029} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[-3.191, 1.485, 0]} rotation={[1.569, 0.182, 0.004]} scale={0.489} />
        <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[-3.333, 1.057, -0.011]} rotation={[1.569, 0.331, -0.008]} scale={0.26} />
        <mesh name="Circle002" geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[-3.174, 1.878, -0.019]} rotation={[1.569, 0.242, -0.008]} scale={0.26} />
        <mesh name="Circle003" geometry={nodes.Circle003.geometry} material={nodes.Circle003.material} position={[-2.492, 1.159, 0.003]} rotation={[1.569, 0.095, 0.005]} scale={0.363} />
        <mesh name="Circle004" geometry={nodes.Circle004.geometry} material={nodes.Circle004.material} position={[-3.014, 1.177, 0.003]} rotation={[1.569, 0.182, 0.004]} scale={0.24} />
        <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={nodes.Circle005.material} position={[-2.689, 1.468, -0.015]} rotation={[1.569, 0.123, -0.007]} scale={0.26} />
        <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={nodes.Circle006.material} position={[2.551, -1.112, 0.025]} rotation={[1.577, 1.055, -0.009]} scale={0.491} />
        <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={nodes.Circle007.material} position={[2.748, -1.448, 0.013]} rotation={[1.589, 1.287, -0.032]} scale={0.261} />
        <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={nodes.Circle008.material} position={[3.189, -1.833, 0.016]} rotation={[1.57, -0.429, -0.002]} scale={0.261} />
        <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={nodes.Circle009.material} position={[3.281, -1.477, 0.029]} rotation={[1.569, 0.095, 0.005]} scale={0.474} />
        <mesh name="Circle010" geometry={nodes.Circle010.geometry} material={nodes.Circle010.material} position={[3.337, -1.028, 0.024]} rotation={[1.569, 0.182, 0.004]} scale={0.256} />
        <mesh name="Circle011" geometry={nodes.Circle011.geometry} material={nodes.Circle011.material} position={[3.038, -1.139, 0.01]} rotation={[1.569, -0.382, -0.003]} scale={0.261} />
        <mesh name="Vert"  material={materials['Material.003']} position={[-0.113, 0.384, -1.082]} rotation={[0.287, -1.114, -1.029]} scale={0.271} />
        <mesh name="Sphere014" geometry={nodes.Sphere014.geometry} material={materials['Material.003']} position={[0.101, 0.103, -0.83]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere009" geometry={nodes.Sphere009.geometry} material={materials['Material.004']} position={[-0.326, -0.178, -0.945]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={materials['Material.003']} position={[0.378, -0.759, -1.275]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere007" geometry={nodes.Sphere007.geometry} material={materials['Material.004']} position={[0.261, -0.534, -1.515]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere006" geometry={nodes.Sphere006.geometry} material={materials['Material.004']} position={[-0.15, -0.59, -0.742]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={materials['Material.003']} position={[-0.099, -0.832, -0.608]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials['Material.004']} position={[0.338, -0.703, -0.934]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials['Material.004']} position={[0.1, -0.307, -0.854]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.003']} position={[0.328, -0.297, -1.179]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.004']} position={[0.095, -0.086, -1.335]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.006']} position={[0.745, -0.894, -0.096]} rotation={[-0.084, 0.908, -3.082]} scale={0.396} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.006']} position={[-0.044, 0.412, -2.474]} rotation={[2.529, 0.133, 0.096]} scale={0.671} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} position={[0.739, -1.338, -0.118]} rotation={[Math.PI, -0.938, Math.PI]} scale={0.36} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.006']} position={[0.003, -1.263, -1.171]} rotation={[0, -1.019, 0]} scale={0.671} />
        <mesh name="Circle014" geometry={nodes.Circle014.geometry} material={materials['Material.002']} position={[0.022, -1.161, -1.179]} rotation={[0.325, -1.125, 0.295]} scale={0.191} />
        <mesh name="BonecoNeve" geometry={nodes.BonecoNeve.geometry} material={materials['Material.005']} position={[-0.483, -1.051, -0.064]} rotation={[0, -1.235, 0]} scale={0.283}>
          <mesh name="Cube002_1" geometry={nodes.Cube002_1.geometry} material={materials['Material.006']} position={[0.742, 0.813, -0.683]} rotation={[-0.17, 0.793, -1.297]} scale={[0.295, 0.086, 0.373]} />
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.006']} position={[0.022, 0.733, -0.005]} scale={[0.954, 0.239, 0.954]} />
          <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.006']} position={[0.022, 0.956, -0.032]} rotation={[-0.124, 0, 0]} scale={[0.923, 0.231, 0.923]} />
          <mesh name="Sphere010" geometry={nodes.Sphere010.geometry} material={materials['Material.005']} position={[0.072, 1.514, -0.099]} scale={0.906}>
            <mesh name="Circle012" geometry={nodes.Circle012.geometry} material={materials['Material.008']} position={[0.879, -0.054, -0.039]} rotation={[1.506, 0.13, -1.388]} scale={0.146} />
            <mesh name="Circle013" geometry={nodes.Circle013.geometry} material={materials['Material.006']} position={[0.021, 0.803, -0.291]} rotation={[-0.38, -0.041, 0]} scale={0.512} />
            <mesh name="Sphere011" geometry={nodes.Sphere011.geometry} material={materials['Material.005']} position={[-0.001, 1.476, -0.538]} scale={0.172} />
            <mesh name="Sphere012" geometry={nodes.Sphere012.geometry} material={materials['Material.007']} position={[0.884, 0.116, -0.316]} scale={0.077} />
          </mesh>
          <mesh name="Sphere016" geometry={nodes.Sphere016.geometry} material={materials['Material.001']} position={[1.081, -0.031, -0.038]} scale={0.088} />
          <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials['Material.005']} position={[0.069, -0.897, -0.003]} scale={[1.51, 0.159, 1.51]} />
        </mesh>
        <mesh name="BezierCurve004" geometry={nodes.BezierCurve004.geometry} material={materials['Material.003']} position={[0.515, -1.502, -1.942]} rotation={[0.018, 0.708, -0.1]} scale={[0.361, 0.419, 0.414]} />
        <mesh name="BezierCurve003" geometry={nodes.BezierCurve003.geometry} material={materials['Material.003']} position={[-0.625, -1.263, -0.693]} rotation={[Math.PI, -1.15, Math.PI]} scale={[0.361, 0.419, 0.414]} />
        <mesh name="BezierCurve002" geometry={nodes.BezierCurve002.geometry} material={materials['Material.001']} position={[-0.182, 0.104, -1.219]} rotation={[0.134, 0.052, -0.128]} scale={[0.119, 0.119, 0.142]} />
        <mesh name="BezierCurve001" geometry={nodes.BezierCurve001.geometry} material={materials['Material.001']} position={[0.169, -0.34, -1.001]} rotation={[-2.991, -0.412, -3.101]} scale={[0.162, 0.162, 0.194]} />
        <mesh name="BezierCurve" geometry={nodes.BezierCurve.geometry} material={materials['Material.001']} position={[0.101, -0.615, -1.418]} rotation={[0.325, -1.125, 0.295]} scale={[0.193, 0.193, 0.231]} />
      </group>
    </group>
  )
}

useGLTF.preload('/src/glb/fleet/FleetCard5.gltf')
