/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/glb/fleet/FleetCard1.gltf 
*/

import React, { useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export default function CenterModel(props) {
  const { nodes, materials } = useGLTF('/src/glb/fleet/FleetCard6.gltf')
  const [scaling, setScaling] = useState(10); 
  const { viewport } = useThree(); 

  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth <= 425) {
        setScaling(3);
      } else if (window.innerWidth <= 1024) {
        setScaling(6);
      } else {
        setScaling(10);
      }
    };

    window.addEventListener("resize", handleResize);

    handleResize();

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []); 
  console.log(viewport.left);
  return (
    <group {...props} dispose={null} scale={viewport.width / scaling}>
      <mesh name="Vert" geometry={nodes.Vert.geometry} material={materials['Material.003']} position={[-0.113, 0.384, -1.082]} rotation={[0.287, -1.114, -1.029]} scale={0.271} />
      <mesh name="Sphere014" geometry={nodes.Sphere014.geometry} material={materials['Material.003']} position={[0.101, 0.103, -0.83]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere009" geometry={nodes.Sphere009.geometry} material={materials['Material.004']} position={[-0.326, -0.178, -0.945]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={materials['Material.003']} position={[0.378, -0.759, -1.275]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere007" geometry={nodes.Sphere007.geometry} material={materials['Material.004']} position={[0.261, -0.534, -1.515]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere006" geometry={nodes.Sphere006.geometry} material={materials['Material.004']} position={[-0.15, -0.59, -0.742]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere005" geometry={nodes.Sphere005.geometry} material={materials['Material.003']} position={[-0.099, -0.832, -0.608]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere004" geometry={nodes.Sphere004.geometry} material={materials['Material.004']} position={[0.338, -0.703, -0.934]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere003" geometry={nodes.Sphere003.geometry} material={materials['Material.004']} position={[0.1, -0.307, -0.854]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.003']} position={[0.328, -0.297, -1.179]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.004']} position={[0.095, -0.086, -1.335]} rotation={[0.325, -1.125, 0.295]} scale={0.072} />
      <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.006']} position={[0.745, -0.894, -0.096]} rotation={[-0.084, 0.908, -3.082]} scale={0.396} />
      <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.006']} position={[-0.044, 0.412, -2.474]} rotation={[2.529, 0.133, 0.096]} scale={0.671} />
      <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.006']} position={[0.739, -1.338, -0.118]} rotation={[Math.PI, -0.938, Math.PI]} scale={0.36} />
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.006']} position={[0.003, -1.263, -1.171]} rotation={[0, -1.019, 0]} scale={0.671} />
      <mesh name="Circle014" geometry={nodes.Circle014.geometry} material={materials['Material.002']} position={[0.022, -1.161, -1.179]} rotation={[0.325, -1.125, 0.295]} scale={0.191} />
      <mesh name="BonecoNeve" geometry={nodes.BonecoNeve.geometry} material={materials['Material.005']} position={[-0.483, -1.051, -0.064]} rotation={[0, -1.235, 0]} scale={0.283}>
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.006']} position={[0.022, 0.733, -0.005]} scale={[0.954, 0.239, 0.954]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.006']} position={[0.022, 0.956, -0.032]} rotation={[-0.124, 0, 0]} scale={[0.923, 0.231, 0.923]} />
        <mesh name="Sphere010" geometry={nodes.Sphere010.geometry} material={materials['Material.005']} position={[0.072, 1.514, -0.099]} scale={0.906}>
          <mesh name="Circle012" geometry={nodes.Circle012.geometry} material={materials['Material.008']} position={[0.879, -0.054, -0.039]} rotation={[1.506, 0.13, -1.388]} scale={0.146} />
          <mesh name="Circle013" geometry={nodes.Circle013.geometry} material={materials['Material.006']} position={[0.021, 0.803, -0.291]} rotation={[-0.38, -0.041, 0]} scale={0.512} />
          <mesh name="Sphere011" geometry={nodes.Sphere011.geometry} material={materials['Material.005']} position={[-0.001, 1.476, -0.538]} scale={0.172} />
          <mesh name="Sphere012" geometry={nodes.Sphere012.geometry} material={materials['Material.007']} position={[0.884, 0.116, -0.316]} scale={0.077} />
        </mesh>
        <mesh name="Sphere016" geometry={nodes.Sphere016.geometry} material={materials['Material.001']} position={[1.081, -0.031, -0.038]} scale={0.088} />
        <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials['Material.005']} position={[0.069, -0.897, -0.003]} scale={[1.51, 0.159, 1.51]} />
      </mesh>
      <mesh name="BezierCurve004" geometry={nodes.BezierCurve004.geometry} material={materials['Material.003']} position={[0.515, -1.502, -1.942]} rotation={[0.018, 0.708, -0.1]} scale={[0.361, 0.419, 0.414]} />
      <mesh name="BezierCurve003" geometry={nodes.BezierCurve003.geometry} material={materials['Material.003']} position={[-0.625, -1.263, -0.693]} rotation={[Math.PI, -1.15, Math.PI]} scale={[0.361, 0.419, 0.414]} />
      <mesh name="BezierCurve002" geometry={nodes.BezierCurve002.geometry} material={materials['Material.001']} position={[-0.182, 0.104, -1.219]} rotation={[0.134, 0.052, -0.128]} scale={[0.119, 0.119, 0.142]} />
      <mesh name="BezierCurve001" geometry={nodes.BezierCurve001.geometry} material={materials['Material.001']} position={[0.169, -0.34, -1.001]} rotation={[-2.991, -0.412, -3.101]} scale={[0.162, 0.162, 0.194]} />
      <mesh name="BezierCurve" geometry={nodes.BezierCurve.geometry} material={materials['Material.001']} position={[0.101, -0.615, -1.418]} rotation={[0.325, -1.125, 0.295]} scale={[0.193, 0.193, 0.231]} />
    </group>
  )
}

useGLTF.preload('/src/glb/fleet/FleetCard6.gltf')
