/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\src\glb\resized-snowglobe.gltf 
*/

import React from 'react'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export default function ScaledSnowGlobe(props) {
  const { nodes, materials } = useGLTF('/src/glb/resized-snowglobe.gltf')
  const { viewport } = useThree();
  return (
    <group {...props} dispose={null} scale={viewport.width / 4} position={[0, -1.5, 0]}>
      <mesh geometry={nodes.build_scenebuild_sceneSnow_Scene_Snow_Globe___Default1_0.geometry} material={materials.PaletteMaterial001} scale={0.048} >
        <MeshTransmissionMaterial
          backsideThickness={8}
          samples={4}
          thickness={0.9}
          anisotropicBlur={0.8}
          ior={1.8}
          iridescence={0.5}
          iridescenceIOR={1}
          iridescenceThicknessRange={[0, 1400]}
          clearcoat={1}
          roughness={0.2}
          envMapIntensity={0.7}
          metalness={0.3}
        />
      </mesh>
      <mesh geometry={nodes.build_scenebuild_sceneSnow_Scene_blinn1_0.geometry} material={materials.PaletteMaterial002} scale={0.048} >
        <meshPhysicalMaterial metalness={0.2} roughness={0.2} color={'white'} envMapIntensity={2} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/resized-snowglobe.gltf')
