/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\src\glb\snowglobe-transformed.glb 
Author: MMKH (https://sketchfab.com/mmkh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/snowglobe-day-11-3dinktober2019-snow-08b4443a71c94647a1298346a1ea1203
Title: Snowglobe - Day 11 #3DInktober2019-Snow
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useThree } from '@react-three/fiber'

export default function SnowGlobeJSX(props) {
  const { nodes, materials } = useGLTF('/src/glb/snowglobe-transformed.glb')
  const {viewport} = useThree();
  return (
    <group {...props} dispose={null} scale={viewport.width/60}>
      <mesh geometry={nodes.build_scenebuild_sceneSnow_Scene_Snow_Globe___Default1_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.build_scenebuild_sceneSnow_Scene_blinn1_0.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/src/glb/snowglobe-transformed.glb')
